name: Docker

on:
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_VERSION }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi
  push:
    Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: checkout
      - uses: actions/checkout@v2

      - name: get denpendencies
      - run: |
          go mod download
          make clean

      - name: Build image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/89trillion/WW4_Server/$IMAGE_NAME

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker push docker.pkg.github.com/89trillion/WW4_Server/$IMAGE_NAME